### ISSUE TITLE
如果我需要用自己的程序,我改修该程序中的哪些地方呢?非常感谢作者的回答

### ISSUE THREAD

**Issue by miraclewxl** [itswcg/DBow_Python#1]
如果我需要用自己的程序,我改修该程序中的哪些地方呢?非常感谢作者的回答

**Comment by jmperdev** [comment]
不好意思，回复晚了，请问你表达的需要用自己的程序是什么意思呢？有问题直接email我，itswcg@gmail.com，可以直接交流。

**Comment by watertianyi** [comment]
你这个代码是DBow的源码python版本吗？离线存储字典，怎么在线加载字典txt呢？

**Comment by jmperdev** [comment]
不是，这只是简单实现的Dbow的python版本，可以生成字典文件在ORM SLAM或DBOW中使用

**Comment by watertianyi** [comment]
txt这个文件怎么使用呢

**Comment by jmperdev** [comment]
你用过orb slam吗？dbow是它其中的一个组成部分，它里面就有需要一个txt字典文件

**Comment by watertianyi** [comment]
目前没有，我主要就是想利用dbow进行相似图判断，txt文档存储的是字典库吧
在线的话相似度判断就是加载这个txt
可以这样理解吗？可以加微信吗，详聊？

**Comment by jmperdev** [comment]
这套程序并没有用到txt文件，这个文件是我生成给orb slam用的，其中的相似度比较都是在内存中的，实时的，没有实现加载字典文件来比较相似度。

**Comment by watertianyi** [comment]
最后代码也给出了比较相似度的分数，我想利用txt，有什么好的建议吗

**Comment by jmperdev** [comment]
那要参考dbow是怎么实现的
